In [1]:
using LinearAlgebra, Test
DEV = true
if DEV    # use local package
    include("../src/EDKit.jl")
    using .EDKit
else      # use EDKit in the Pkg system
    using EDKit
end

## Translation Basis

In [2]:
# Use to show digit
function printdgt!(B)
    num = size(B, 1)
    if iszero(num)
        println("Nothing")
    else
        for i in 1:size(B, 1)
            change!(B, i)
            print("|"); print.(B.dgt); print("⟩, ") 
        end
        print("\n")
    end
end;

In [3]:
function show_info_1(L, N, k, a)
    println("-----------------------\nL=$L, N=$N, k=$k, a=$a:\n-----------------------");
    basis = TranslationalBasis(L=L, k=k, N=N, a=a)
    print("Digit: ")
    printdgt!(basis)
    print("Norm : ")
    println(basis.R);
    basis
end

@testset "Charge-conserving" begin
    b = show_info(4, 0, 0, 1)
    @test size(b, 1) == 1
    @test norm(b, 1) ≈ 4

    b = show_info(4, 0, 1, 1)
    @test size(b, 1) == 0

    b = show_info(4, 0, 1, 2)
    @test size(b, 1) ≈ 0

    b = show_info(4, 1, 0, 1)
    @test size(b, 1) == 1
    @test norm(b, 1) ≈ 2

    b = show_info(4, 1, 1, 1)
    @test size(b, 1) == 1
    @test norm(b, 1) ≈ 2

    b = show_info(4, 1, 0, 2)
    @test size(b, 1) == 2
    @test norm(b, 1) ≈ sqrt(2)

    b = show_info(4, 1, 1, 2)
    @test size(b, 1) == 2
    @test norm(b, 1) ≈ sqrt(2)
end;

Charge-conserving: Error During Test at 

/Users/ren/Documents/GitHub/EDKit/test/Translation.ipynb:11
  Got exception outside of a @test
  UndefVarError: `show_info` not defined
  Stacktrace:
    [1] macro expansion
      @ ~/Documents/GitHub/EDKit/test/Translation.ipynb:12 [inlined]
    [2] macro expansion
      @ /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
    [3] top-level scope
      @ ~/Documents/GitHub/EDKit/test/Translation.ipynb:12
    [4] eval
      @ ./boot.jl:370 [inlined]
    [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
      @ Base ./loading.jl:1864
    [6] #invokelatest#2
      @ ./essentials.jl:816 [inlined]
    [7] invokelatest
      @ ./essentials.jl:813 [inlined]
    [8] (::VSCodeServer.var"#198#199"{VSCodeServer.NotebookRunCellArguments, String})()
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.47.2/scripts/packages/VSCodeServer/src/serve_notebook.jl:19
    [9] withpath(f

Error  Total  Time
Charge-conserving |     1      1  0.6s


TestSetException: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.

## TranslationParity

In [4]:
function show_info(;L, N, k, p, a)
    println("-----------------------\nL=$L, N=$N, k=$k, p=$p, a=$a:\n-----------------------");
    basis = TranslationParityBasis(L=L, k=k, N=N, p=p, a=a)
    print("Digit: ")
    printdgt!(basis)
    print("Norm : ")
    println(basis.R);
    basis
end

@testset "Charge-conserving" begin
    b = show_info(L=4, N=0, k=0, p=1, a=1)
    #@test size(b, 1) == 1
    #@test norm(b, 1) ≈ 8

    b = show_info(L=4, N=0, k=0, p=-1, a=1)
    #@test size(b, 1) == 0

    b = show_info(L=4, N=0, k=2, p=1, a=1)
    #@test size(b, 1) == 0

    b = show_info(L=2, N=1, k=0, p=1, a=1)
    #@test size(b, 1) == 1
end;

-----------------------
L=4, N=0, k=0, p=1, a=1:
-----------------------
Digit: |0000⟩, 
Norm : 

[8.0]
-----------------------
L=4, N=0, k=0, p=-1, a=1:
-----------------------
Digit: Nothing
Norm : Float64[]
-----------------------
L=4, N=0, k=2, p=1, a=1:
-----------------------
Digit: Nothing
Norm : Float64[]
-----------------------
L=2, N=1, k=0, p=1, a=1:
-----------------------
Digit: |01⟩, 
Norm : [2.82842712474619]
Test Summary:     |Time
Charge-conserving | None  0.5s


In [5]:
b = show_info(L=2, N=1, k=1, p=-1, a=1)

-----------------------
L=2, N=1, k=1, p=-1, a=1:
-----------------------
Digit: |01⟩, 
Norm : [2.82842712474619]


TranslationParityBasis{Int64}([0, 1], [2], [2.82842712474619], [1, -1], -1, 1, 2)

In [6]:
function show_info_1(;L, N, k, a)
    println("-----------------------\nL=$L, N=$N, k=$k, a=$a:\n-----------------------");
    basis = TranslationalBasis(L=L, k=k, N=N, a=a)
    print("Digit: ")
    printdgt!(basis)
    print("Norm : ")
    println(basis.R);
    basis
end

b = show_info_1(L=5, N=2, k=1, a=1)

-----------------------
L=5, N=2, k=1, a=1:
-----------------------
Digit: |00011⟩, |00101⟩, 
Norm : [2.23606797749979, 2.23606797749979]


TranslationalBasis{Int64, ComplexF64}([0, 0, 1, 0, 1], [4, 6], [2.23606797749979, 2.23606797749979], ComplexF64[1.0 - 0.0im, 0.30901699437494745 - 0.9510565162951535im, -0.8090169943749473 - 0.5877852522924732im, -0.8090169943749475 + 0.587785252292473im, 0.30901699437494723 + 0.9510565162951536im], 1, 2)

In [30]:
b = show_info_1(L=2, N=1, k=1, a=1);

-----------------------
L=2, N=1, k=1, a=1:
-----------------------
Digit: |01⟩, 
Norm : [1.414213562373095]


In [35]:
v = [1]
EDKit.schmidt(v, 1:1, b)

2×2 Matrix{Float64}:
  0.0       0.707107
 -0.707107  0.0

In [34]:
val = EDKit.ent_spec(v, 1:1, b)

2-element Vector{Float64}:
 0.7071067811865476
 0.7071067811865476

In [36]:
v = [0, 1, 1, 0] |> normalize
EDKit.schmidt(v, 1:1, TensorBasis(L=2))

2×2 Matrix{Float64}:
 0.0       0.707107
 0.707107  0.0

In [48]:
b = TranslationalBasis(L=10,N=5,k=0)
v = ones(size(b,1))|>normalize
ent_S(v,1:5,b)

1.276653692689251

In [39]:
b

TranslationalBasis{Int64, Float64}([0, 1], [2], [1.414213562373095], [1.0, -1.0], 1, 2)

In [46]:
b = TranslationalBasis(L=10, N=2, k=1)

TranslationalBasis{Int64, ComplexF64}([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [4, 6, 10, 18], [3.162277660168379, 3.162277660168379, 3.162277660168379, 3.162277660168379], ComplexF64[1.0 - 0.0im, 0.8090169943749475 - 0.5877852522924731im, 0.30901699437494745 - 0.9510565162951535im, -0.30901699437494734 - 0.9510565162951536im, -0.8090169943749473 - 0.5877852522924732im, -1.0 - 1.2246467991473532e-16im, -0.8090169943749475 + 0.587785252292473im, -0.30901699437494756 + 0.9510565162951535im, 0.30901699437494723 + 0.9510565162951536im, 0.8090169943749473 + 0.5877852522924734im], 1, 2)

In [47]:
ent_spec([1], 1:5, b)

32-element Vector{Float64}:
 0.6324555320336759
 0.6324555320336758
 0.31622776601683794
 0.31622776601683783
 4.3186812173721336e-17
 2.652093457054458e-17
 3.74882337563857e-18
 1.330283059320525e-33
 4.850162514562787e-34
 3.656382187162855e-50
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [49]:
L = 6
h = rand()
rh = begin
    vecs = zeros(ComplexF64, 9, 4)
    vecs[8,1] = 1
    vecs[6,1] = -1
    vecs[7,2] = 1
    vecs[3,2] = -1
    vecs[4,3] = 1
    vecs[2,3] = -1
    vecs[3,4] = 1
    vecs[5,4] = -1
    vecs[7,4] = 1
    rm = rand(ComplexF64, 4,4) .- 0.5 |> Hermitian |> Array
    vecs * rm * vecs'
end
H  = trans_inv_operator(rh, 2, L)
H += trans_inv_operator(spin((h, "z"), D=3), 1, L)
E, V = Array(H) |> Hermitian |> eigen

inds = 1:L÷2
ts = Float64[]
for i = 0:L-1
    tb = TranslationalBasis(k=i, L=L, base = 3)
    H  = trans_inv_operator(rh, 2, tb)
    H += trans_inv_operator(spin((h, "z"), D=3), 1, tb)
    e, v = Array(H) |> Hermitian |> eigen
    ee = [ent_S(v[:, i], inds, tb) for i=1:size(v, 2)]
    append!(ts, ee)
end
EE = [ent_S(V[:, i], inds, TensorBasis(L=L, base=3)) for i=1:size(V, 2)]

729-element Vector{Float64}:
 1.190829532682147
 1.1471017782144701
 1.460799538176479
 1.360292172757131
 1.7661644475790872
 1.4580658177877375
 1.7281899667746141
 1.2473947239511438
 1.7847288658295795
 1.7354639670749357
 ⋮
 1.7521370660823137
 1.6407390922655605
 1.6676265842041675
 1.6868661733332624
 1.6539074083059968
 1.256446310545011
 1.0333260253871897
 1.1222391204100453
 1.1302646584176896

In [50]:
h

0.44685977903125884

In [74]:
i = 2
tb = TranslationalBasis(k=i, L=L, base=3)
H  = trans_inv_operator(rh, 2, tb)
H += trans_inv_operator(spin((h, "z"), D=3), 1, tb)
e, v = Array(H) |> Hermitian |> eigen
ee = [ent_S(v[:, i], inds, tb) for i=1:size(v, 2)]
print(ee)

[1.732765167249634, 2.2679922711636498, 2.37259923477273, 2.362499468504235, 2.340655967560863, 2.4106750174478413, 2.369033630225111, 2.5089575362355583, 2.5180742627508423, 2.463625881993398, 2.587105911563905, 2.5792730929667917, 2.534534821499161, 2.5222926267401817, 2.5855545205461086, 2.6160537388000633, 2.5981813230398014, 2.590168204819945, 2.5737053838612725, 2.676982335901359, 2.7015250926243133, 2.698710124829857, 2.6545743215153066, 2.675420710352485, 2.715202947712499, 2.6726367111046545, 2.6944245529623694, 2.70265088621532, 2.4913609563650225, 2.588053729848057, 2.7311490339793, 2.342570410016261, 2.652913598402467, 2.701742958652652, 2.5426187217992973, 2.6820423755730025, 2.776460920140795, 2.788808453575073, 2.733426196386697, 2.762037731231172, 2.7280639942522784, 2.7261698802595618, 2.7556256219379613, 2.660403049924625, 2.7363449176766754, 1.5244853358843027, 2.803645767946231, 2.8125940806990917, 2.740725199543008, 2.689965878315516, 2.7882392802482046, 2.05021852

In [82]:
trans_inv_operator(rh, 2, tb) |> Hermitian |> eigvals

124-element Vector{Float64}:
 -10.795258437626782
 -10.009427207319266
  -8.946444583375543
  -8.088096317002444
  -7.961777309677815
  -7.276263664499716
  -6.9945578285978165
  -6.795394771310527
  -6.271330868568793
  -6.1866919259785895
   ⋮
   4.329364103958257
   4.463421488060556
   4.782813560002337
   4.974215132194553
   5.062931429671648
   5.489234767146038
   6.13030897604012
   6.494644494017515
   7.141104679321491

In [78]:
print(rh)

ComplexF64[0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im -0.1843003682801232 + 0.0im 0.03009774994789305 - 1.2621121358872887im 0.1843003682801232 + 0.0im -0.40858044473669597 + 0.9148120365983794im -0.4103841666107012 - 0.32744632068191437im 0.7870631395254989 - 0.5675119373094701im 0.4103841666107012 + 0.32744632068191437im 0.0 + 0.0im; 0.0 + 0.0im 0.03009774994789305 + 1.2621121358872887im -1.1799421489083886 + 0.0im -0.03009774994789305 - 1.2621121358872887im 0.6598017545545928 + 0.389999548416467im -0.4373438978697294 - 0.16942942711436093im -0.139661360200797 - 0.779999096832934im 0.4373438978697294 + 0.16942942711436093im 0.0 + 0.0im; 0.0 + 0.0im 0.1843003682801232 + 0.0im -0.03009774994789305 + 1.2621121358872887im -0.1843003682801232 + 0.0im 0.40858044473669597 - 0.9148120365983794im 0.4103841666107012 + 0.32744632068191437im -0.7870631395254989 + 0.5675119373094701im -0.4103841666107012 - 0.32744632068

In [84]:
print(rh)

ComplexF64[0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im -0.1843003682801232 + 0.0im 0.03009774994789305 - 1.2621121358872887im 0.1843003682801232 + 0.0im -0.40858044473669597 + 0.9148120365983794im -0.4103841666107012 - 0.32744632068191437im 0.7870631395254989 - 0.5675119373094701im 0.4103841666107012 + 0.32744632068191437im 0.0 + 0.0im; 0.0 + 0.0im 0.03009774994789305 + 1.2621121358872887im -1.1799421489083886 + 0.0im -0.03009774994789305 - 1.2621121358872887im 0.6598017545545928 + 0.389999548416467im -0.4373438978697294 - 0.16942942711436093im -0.139661360200797 - 0.779999096832934im 0.4373438978697294 + 0.16942942711436093im 0.0 + 0.0im; 0.0 + 0.0im 0.1843003682801232 + 0.0im -0.03009774994789305 + 1.2621121358872887im -0.1843003682801232 + 0.0im 0.40858044473669597 - 0.9148120365983794im 0.4103841666107012 + 0.32744632068191437im -0.7870631395254989 + 0.5675119373094701im -0.4103841666107012 - 0.32744632068