# Quantum Inverse method

We will use the `Optim.jl` package for auto-diff optimization, and the `EDKit.jl` for exact diagonalization calculation.

In [1]:
using LinearAlgebra
include("../src/EDKit.jl")
using Main.EDKit

In [2]:
opl = [
    spin("xx"), spin("xy"), spin("xz"),
    spin("yx"), spin("yy"), spin("yz"), 
    spin("zx"), spin("zy"), spin("zz")
]

function target(B)
    L = length(B)
    m = zeros(size(B,1), L+1)
    sm = trans_inv_operator("-", B)
    m[1,1] = 1.0
    for i in 1:L
        m[:, i+1] = sm * m[:, i] |> normalize!
    end
    m
end

target (generic function with 1 method)

In [5]:
B = TensorBasis(L=10)
qimsolve([trans_inv_operator(o, 2, B) for o in opl], target(B))

9×4 Matrix{Float64}:
  0.0   0.0   0.0  1.0
  1.0   0.0   0.0  0.0
  0.0   1.0   0.0  0.0
 -1.0   0.0   0.0  0.0
  0.0   0.0   0.0  1.0
  0.0   0.0   1.0  0.0
  0.0  -1.0   0.0  0.0
  0.0   0.0  -1.0  0.0
  0.0   0.0   0.0  1.0

In [6]:
B = TranslationalBasis(L=10)
qimsolve([trans_inv_operator(o, 2, B) for o in opl], target(B))

9×4 Matrix{Float64}:
  0.0  1.0   0.0   0.0
  1.0  0.0   0.0   0.0
  0.0  0.0   0.0   1.0
 -1.0  0.0   0.0   0.0
  0.0  1.0   0.0   0.0
  0.0  0.0   1.0   0.0
  0.0  0.0   0.0  -1.0
  0.0  0.0  -1.0   0.0
  0.0  1.0   0.0   0.0

In [7]:
B = TranslationParityBasis(L=10,p=1)
qimsolve([trans_inv_operator(o, 2, B) for o in opl], target(B))

9×1 Matrix{Float64}:
 1.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 1.0000000000000004